### PR TITLE
New handler for KeyError

### PR DESCRIPTION
**Pull request by marceloFA**
This pull request adds a new handler for the KeyError exception. 
Additions:
- KeyError now is manually handled as it is quite a simple error with only one possible origin (user tried to access a key of a dict that does not exist);
- Tests for the new handler were added;
- A pycee_answer feature was added to the usage example, to illustrate that simpler errors can be handled without Stackoverflow;

### CODE REVIEW

**Comment by marceloFA** [comment]
@LeonardoFurtado, when the time comes, please squash and merge to keep the history tree clean. Thank you ❤

**Review by LeonardoFurtado — CHANGES_REQUESTED** [review]
For large commits like this, we need more descriptive commit messages. Something like:
```
Describe the commit in a short sentence fragment
    ----blank line-----
This is an example commit message. The first line is a short summary. The second line is blank. The third line (this line) is a longer paragraph explaining the changes in the commit.
```
You can force push a commit with an amended message to rewrite that commit.

**Review by LeonardoFurtado — COMMENTED** [review]
I appreciate these new tests :sunglasses:

**Review by LeonardoFurtado — CHANGES_REQUESTED** [review]
Same here, a more descriptive commit

**Comment by marceloFA** [comment]
Commit messages added. Nice touch, thank you. I'll make this standard for now on.

**Review by LeonardoFurtado — APPROVED** [review]

**Comment by LeonardoFurtado** [comment]
> 
> 
> Commit messages added. Nice touch, thank you. I'll make this standard from now on.

These commit comments are very useful for code changes, they can be ignored for simpler actions like changing a badge, fixi a typo, move code snippet, etc.

Nice work :tada:

**Comment by LeonardoFurtado** [comment]
> 
> 
> Commit messages added. Nice touch, thank you. I'll make this standard from now on.

@marceloFA  if there is nothing else to do, delete your branch ;)

**Pull request merged**
